# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e2e836d4344113ffd8f52769e5f5e626f1d49c04cb5a70827dfb062db2ebb3cbdd007c5fcd0dd15b9e1560f06220a857381c025670e0e47a0ad0ea1d73daa8

test:
  secret_key_base: 8e633738dcc9dce2a3f85ef5e312fa343dcb0af13c704715f9ac7d95e7d81b0af396cbe2815714cad782e173f300d30bad802d175b3892d71f6bfb349bfa9ae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
